### ISSUE TITLE
Does not work with ipywidgets 7.8.0

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-ipywidgets#37]
I would like to be able to use deephaven-ipywidgets with 7.8.0

**Comment by mofojed** [comment]
Tried it out, the error I'm getting:
```
272.2c7a2a1ef6d577414e03.js:1 Failed to fetch ipywidgets through the "jupyter.widget.control" comm channel, fallback to fetching individual model state. Reason: Control comm was closed too early
(anonymous) @ 272.2c7a2a1ef6d577414e03.js:1
11:55:55.801 523.6e13edd0a9dd3788d5ec.js:1 Uncaught (in promise) TypeError: e.metadata.get is not a function
    at x._loadFromNotebook (523.6e13edd0a9dd3788d5ec.js:1:4630)
    at x.restoreWidgets (523.6e13edd0a9dd3788d5ec.js:1:4201)
11:57:30.118 272.2c7a2a1ef6d577414e03.js:1 Error: Could not create a view for model id d3f5c38e4e114a359127ea799d4ff39e
    at 272.2c7a2a1ef6d577414e03.js:1:2224
(anonymous) @ 272.2c7a2a1ef6d577414e03.js:1
11:57:30.118 272.2c7a2a1ef6d577414e03.js:1 Error: Could not create view
    at 272.2c7a2a1ef6d577414e03.js:1:2224
    at async u.renderModel (523.6e13edd0a9dd3788d5ec.js:1:1215)
(anonymous) @ 272.2c7a2a1ef6d577414e03.js:1
11:57:30.118 523.6e13edd0a9dd3788d5ec.js:1 TypeError: Class constructor E cannot be invoked without 'new'
    at new t (272.2c7a2a1ef6d577414e03.js:1:27441)
    at t._setElement (272.2c7a2a1ef6d577414e03.js:1:30545)
    at DeephavenView.setElement (803.b7b75bd6e7977a648c67.js:1:14110)
    at DeephavenView._ensureElement (803.b7b75bd6e7977a648c67.js:1:15010)
    at e.View (803.b7b75bd6e7977a648c67.js:1:13646)
    at DeephavenView.t [as constructor] (272.2c7a2a1ef6d577414e03.js:1:17153)
    at DeephavenView.t [as constructor] (272.2c7a2a1ef6d577414e03.js:1:26171)
    at new t (272.2c7a2a1ef6d577414e03.js:1:28170)
    at new DeephavenView (widget.ts:64:5)
    at 272.2c7a2a1ef6d577414e03.js:1:6878
renderModel @ 523.6e13edd0a9dd3788d5ec.js:1
11:57:30.120 272.2c7a2a1ef6d577414e03.js:1 Uncaught (in promise) TypeError: Class constructor E cannot be invoked without 'new'
    at new t (272.2c7a2a1ef6d577414e03.js:1:27441)
    at t._setElement (272.2c7a2a1ef6d577414e03.js:1:30545)
    at DeephavenView.setElement (803.b7b75bd6e7977a648c67.js:1:14110)
    at DeephavenView._ensureElement (803.b7b75bd6e7977a648c67.js:1:15010)
    at e.View (803.b7b75bd6e7977a648c67.js:1:13646)
    at DeephavenView.t [as constructor] (272.2c7a2a1ef6d577414e03.js:1:17153)
    at DeephavenView.t [as constructor] (272.2c7a2a1ef6d577414e03.js:1:26171)
    at new t (272.2c7a2a1ef6d577414e03.js:1:28170)
    at new DeephavenView (widget.ts:64:5)
    at 272.2c7a2a1ef6d577414e03.js:1:6878
```
